/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Chair3(props) {
  const { nodes, materials } = useGLTF('/ImageToStl.com_dining table.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes.Mirror7_0.geometry}
        material={materials.__DEFAULT}>
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LPattern310_1.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LPattern37_2.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LPattern39_3.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LPattern311_4.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LPattern38_5.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LPattern37_6.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet1_7.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LPattern36_8.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LPattern34_9.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LPattern31_10.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LPattern33_11.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LPattern35_12.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LPattern32_13.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NONE_14.geometry}
          material={materials.__DEFAULT}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NONE_15.geometry}
          material={materials.__DEFAULT}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes['Extrude-Thin2_16'].geometry}
          material={materials.__DEFAULT}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Mirror8_17.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet1_18.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LPattern36_19.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LPattern34_20.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LPattern31_21.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LPattern33_22.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LPattern35_23.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.LPattern32_24.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.Fillet2_25.geometry}
          material={materials['African teak polished']}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NONE_26.geometry}
          material={materials.__DEFAULT}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NONE_27.geometry}
          material={materials.__DEFAULT}
        />
        <mesh
          castShadow
          receiveShadow
          geometry={nodes.NONE_28.geometry}
          material={materials['Satin Platinum']}
        />
      </mesh>
    </group>
  )
}

useGLTF.preload('/ImageToStl.com_dining table.glb')

