/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export function Chair4(props) {
  const { nodes, materials } = useGLTF('/ImageToStl.com_center table.glb')
  return (
    <group {...props} dispose={null}>
      <mesh
        castShadow
        receiveShadow
        geometry={nodes._0.geometry}
        material={materials.c31731abc25431ef46d16e5f7afda68e}>
        <mesh castShadow receiveShadow geometry={nodes._1.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._2.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._3.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._4.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._5.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._6.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._7.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._8.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._9.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._10.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._11.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._12.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._13.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._14.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._15.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._16.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._17.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._18.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._19.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._20.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._21.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._22.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._23.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._24.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._25.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._26.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._27.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._28.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._29.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._30.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._31.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._32.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._33.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._34.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._35.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._36.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._37.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._38.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._39.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._40.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._41.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._42.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._43.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._44.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._45.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._46.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._47.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._48.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._49.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._50.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._51.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._52.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._53.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._54.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._55.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._56.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._57.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._58.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._59.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._60.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._61.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._62.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._63.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._64.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._65.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._66.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._67.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._68.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._69.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._70.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._71.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._72.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._73.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._74.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._75.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._76.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._77.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._78.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._79.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._80.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._81.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._82.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._83.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._84.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._85.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._86.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._87.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._88.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._89.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._90.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._91.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._92.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._93.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._94.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._95.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._96.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._97.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._98.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._99.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._100.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._101.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._102.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._103.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._104.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._105.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._106.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._107.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._108.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._109.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._110.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._111.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._112.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._113.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._114.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._115.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._116.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._117.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._118.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._119.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._120.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._121.geometry} material={materials.Metal} />
        <mesh castShadow receiveShadow geometry={nodes._122.geometry} material={materials.Metal} />
      </mesh>
    </group>
  )
}

useGLTF.preload('/ImageToStl.com_center table.glb')



